<center>
    <img src="https://gitlab.com/ibm/skills-network/courses/placeholder101/-/raw/master/labs/module%201/images/IDSNlogo.png" width="300" alt="cognitiveclass.ai logo"  />
</center>

# **Data Wrangling Lab**

Estimated time needed: **45 to 60** minutes

In this assignment you will be performing data wrangling.

## Objectives

In this lab you will perform the following:

*   Identify duplicate values in the dataset.

*   Remove duplicate values from the dataset.

*   Identify missing values in the dataset.

*   Impute the missing values in the dataset.

*   Normalize data in the dataset.

<hr>

## Hands on Lab

Import pandas module.

In [1]:
import pandas as pd

Load the dataset into a dataframe.

In [2]:
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/LargeData/m1_survey_data.csv")

## Finding duplicates

In this section you will identify duplicate values in the dataset.

Find how many duplicate rows exist in the dataframe.

In [5]:
# your code goes here
df.duplicated().sum()

154

## Removing duplicates

Remove the duplicate rows from the dataframe.

In [6]:
# your code goes here
df = df.drop_duplicates()

Verify if duplicates were actually dropped.

In [7]:
# your code goes here
df.duplicated().sum()

0

In [27]:
df['EdLevel'].isnull().sum()

112

In [28]:
df['Country'].isnull().sum()

0

## Finding Missing values

Find the missing values for all columns.

In [8]:
# your code goes here
df.isnull().sum()

Respondent        0
MainBranch        0
Hobbyist          0
OpenSourcer       0
OpenSource       81
               ...
Sexuality       542
Ethnicity       675
Dependents      140
SurveyLength     19
SurveyEase       14
Length: 85, dtype: int64

Find out how many rows are missing in the column 'WorkLoc'

In [10]:
# your code goes here
df['WorkLoc'].isnull().sum()

32

## Imputing missing values

Find the  value counts for the column WorkLoc.

In [11]:
# your code goes here
df['WorkLoc'].value_counts()

Office                                            6806
Home                                              3589
Other place, such as a coworking space or cafe     971
Name: WorkLoc, dtype: int64

Identify the value that is most frequent (majority) in the WorkLoc column.

In [13]:
#make a note of the majority value here, for future reference
#
df['WorkLoc'].value_counts().idxmax()

'Office'

In [30]:
df['Employment'].value_counts().idxmax()

'Employed full-time'

In [31]:
df['UndergradMajor'].value_counts().idxmin()

'A health science (ex. nursing, pharmacy, radiology)'

Impute (replace) all the empty rows in the column WorkLoc with the value that you have identified as majority.

In [14]:
# your code goes here
df['WorkLoc'] = df['WorkLoc'].fillna('office')

/tmp/wsuser/ipykernel_1049/1009661559.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['WorkLoc'] = df['WorkLoc'].fillna('office')

After imputation there should ideally not be any empty rows in the WorkLoc column.

Verify if imputing was successful.

In [15]:
# your code goes here
df['WorkLoc'].isnull().sum()

0

## Normalizing data

There are two columns in the dataset that talk about compensation.

One is "CompFreq". This column shows how often a developer is paid (Yearly, Monthly, Weekly).

The other is "CompTotal". This column talks about how much the developer is paid per Year, Month, or Week depending upon his/her "CompFreq".

This makes it difficult to compare the total compensation of the developers.

In this section you will create a new column called 'NormalizedAnnualCompensation' which contains the 'Annual Compensation' irrespective of the 'CompFreq'.

Once this column is ready, it makes comparison of salaries easy.

<hr>

List out the various categories in the column 'CompFreq'

In [19]:
# your code goes here
df['CompFreq'].value_counts().index

Index(['Yearly', 'Monthly', 'Weekly'], dtype='object')

In [32]:
df['CompFreq'].nunique()

3

Create a new column named 'NormalizedAnnualCompensation'. Use the hint given below if needed.

Double click to see the **Hint**.

<!--

Use the below logic to arrive at the values for the column NormalizedAnnualCompensation.

If the CompFreq is Yearly then use the exising value in CompTotal
If the CompFreq is Monthly then multiply the value in CompTotal with 12 (months in an year)
If the CompFreq is Weekly then multiply the value in CompTotal with 52 (weeks in an year)

-->

In [23]:
# your code goes here
annual = []
def annualcomp():
    for x,y in zip(df['CompFreq'], df['CompTotal']):
        if x=="Monthly":
            annual.append(y*12)
        elif x=="Weekly":
            annual.append(y*52)
        else:
            annual.append(y)
annualcomp()

In [24]:
df['NormalizedAnnualCompensation'] = annual

/tmp/wsuser/ipykernel_1049/3056946149.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['NormalizedAnnualCompensation'] = annual

In [25]:
df[['NormalizedAnnualCompensation']]

       NormalizedAnnualCompensation
0                           61000.0
1                          138000.0
2                           90000.0
3                          348000.0
4                           90000.0
...                             ...
11547                      130000.0
11548                       74400.0
11549                      105000.0
11550                       80000.0
11551                           NaN

[11398 rows x 1 columns]

In [33]:
df['NormalizedAnnualCompensation'].median()

100000.0

## Authors

In [26]:
df.shape

(11398, 86)

Ramesh Sannareddy

### Other Contributors

Rav Ahuja

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By        | Change Description                 |
| ----------------- | ------- | ----------------- | ---------------------------------- |
| 2020-10-17        | 0.1     | Ramesh Sannareddy | Created initial version of the lab |

Copyright © 2020 IBM Corporation. This notebook and its source code are released under the terms of the [MIT License](https://cognitiveclass.ai/mit-license?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork21426264-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ).